### ISSUE TITLE
Ensure that the project builds without error

### ISSUE THREAD

**Issue by jleach** [fullboar/vc-showcase#3]
The project should build `yarn run build` without error:

- [x] No typescript / tsc errors;
- [x] No eslint errors.

**Comment by crazy-dev-git** [comment]
@jleach
Let me resolve this issue, please assign this task to me.

**Comment by MAhmedSaeedi** [comment]
Hi @jleach. I have fixed the issues mentioned here for the **web** directory. It is being compiled and built succesfully. I can create a PR if I am allowed. Thanks
